--1. The Eq class c) makes equality tests possible
--2. The type class Ord b) is a subclass of Eq
--3. Suppose the type class Ord has an operator >. What is the type of >? a) Ord a => a -> a -> Bool
--4. In x = divMod 16 12 c) the type is a tuple
--5 The type class Integral includes a) Int and Integer numbers